version: "2.1"
services:
  web:
    container_name: web
    build: .
    volumes: [".:/app"]
    ports: ["3000:3000"]
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/amigo
      DATABASE_TEST_URL: postgres://postgres:password@testdb:5432/amigo_test
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=amigo
    healthcheck:
      test: exit 0